# Generated by Django 4.2.16 on 2024-11-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='book',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
